[font]
size = 9.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 1
y = 1

[selection]
save_to_clipboard = true


# keyboard bindings
[keyboard]
bindings = [
    { key = "N", mods = "Control", action = "SpawnNewInstance" },
]
